//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Alterações neste arquivo podem causar comportamento incorreto e serão perdidas
//     se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable

namespace AcademiaDoZe.Presentation.AppMaui.Resources.Strings;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class AppResources
{
    private static global::System.Resources.ResourceManager resourceMan;
    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal AppResources()
    {
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcademiaDoZe.Presentation.AppMaui.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string strTitulo => ResourceManager.GetString("strTitulo", resourceCulture);
    public static string strSubTitulo => ResourceManager.GetString("strSubTitulo", resourceCulture);
    public static string strDashboard => ResourceManager.GetString("strDashboard", resourceCulture);
    public static string strLogradouro => ResourceManager.GetString("strLogradouro", resourceCulture);
    public static string strAluno => ResourceManager.GetString("strAluno", resourceCulture);
    public static string strColaborador => ResourceManager.GetString("strColaborador", resourceCulture);
    public static string strMatricula => ResourceManager.GetString("strMatricula", resourceCulture);
    public static string strAcesso => ResourceManager.GetString("strAcesso", resourceCulture);
    public static string strBemVindo => ResourceManager.GetString("strBemVindo", resourceCulture);
    public static string strDashboardDescricao => ResourceManager.GetString("strDashboardDescricao", resourceCulture);
    public static string strIdioma => ResourceManager.GetString("strIdioma", resourceCulture);
    public static string strSalvar => ResourceManager.GetString("strSalvar", resourceCulture);
    public static string strCancelar => ResourceManager.GetString("strCancelar", resourceCulture);
    public static string strExcluir => ResourceManager.GetString("strExcluir", resourceCulture);
    public static string strEditar => ResourceManager.GetString("strEditar", resourceCulture);
    public static string strBuscar => ResourceManager.GetString("strBuscar", resourceCulture);
    public static string strAtualizar => ResourceManager.GetString("strAtualizar", resourceCulture);
    public static string strTotalRegistros => ResourceManager.GetString("strTotalRegistros", resourceCulture);
}
