//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Alterações neste arquivo podem causar comportamento incorreto e serão perdidas
//     se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable

namespace AcademiaDoZe.Presentation.AppMaui.Resources.Strings;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class AppResources
{
    private static global::System.Resources.ResourceManager resourceMan;
    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal AppResources()
    {
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcademiaDoZe.Presentation.AppMaui.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string strTitulo => ResourceManager.GetString("strTitulo", resourceCulture);
    public static string strSubTitulo => ResourceManager.GetString("strSubTitulo", resourceCulture);
    public static string strDashboard => ResourceManager.GetString("strDashboard", resourceCulture);
    public static string strLogradouro => ResourceManager.GetString("strLogradouro", resourceCulture);
    public static string strAluno => ResourceManager.GetString("strAluno", resourceCulture);
    public static string strColaborador => ResourceManager.GetString("strColaborador", resourceCulture);
    public static string strMatricula => ResourceManager.GetString("strMatricula", resourceCulture);
    public static string strAcesso => ResourceManager.GetString("strAcesso", resourceCulture);
    public static string strBemVindo => ResourceManager.GetString("strBemVindo", resourceCulture);
    public static string strDashboardDescricao => ResourceManager.GetString("strDashboardDescricao", resourceCulture);
    public static string strIdioma => ResourceManager.GetString("strIdioma", resourceCulture);
    public static string strSalvar => ResourceManager.GetString("strSalvar", resourceCulture);
    public static string strCancelar => ResourceManager.GetString("strCancelar", resourceCulture);
    public static string strExcluir => ResourceManager.GetString("strExcluir", resourceCulture);
    public static string strEditar => ResourceManager.GetString("strEditar", resourceCulture);
    public static string strBuscar => ResourceManager.GetString("strBuscar", resourceCulture);
    public static string strAtualizar => ResourceManager.GetString("strAtualizar", resourceCulture);
    public static string strTotalRegistros => ResourceManager.GetString("strTotalRegistros", resourceCulture);
    public static string strAtivas => ResourceManager.GetString("strAtivas", resourceCulture);
    public static string strTema => ResourceManager.GetString("strTema", resourceCulture);
    public static string strTemaSistema => ResourceManager.GetString("strTemaSistema", resourceCulture);
    public static string strTemaClaro => ResourceManager.GetString("strTemaClaro", resourceCulture);
    public static string strTemaEscuro => ResourceManager.GetString("strTemaEscuro", resourceCulture);
    public static string strConfiguracoes => ResourceManager.GetString("strConfiguracoes", resourceCulture);
    public static string strConfiguracoesDescricao => ResourceManager.GetString("strConfiguracoesDescricao", resourceCulture);
    public static string strVoltar => ResourceManager.GetString("strVoltar", resourceCulture);
    public static string strTemaDescricao => ResourceManager.GetString("strTemaDescricao", resourceCulture);
    public static string strSalvarTema => ResourceManager.GetString("strSalvarTema", resourceCulture);
    public static string strCredenciaisBanco => ResourceManager.GetString("strCredenciaisBanco", resourceCulture);
    public static string strCredenciaisBancoDescricao => ResourceManager.GetString("strCredenciaisBancoDescricao", resourceCulture);
    public static string strTipoGerenciador => ResourceManager.GetString("strTipoGerenciador", resourceCulture);
    public static string strAvisoSqlite => ResourceManager.GetString("strAvisoSqlite", resourceCulture);
    public static string strCaminhoBanco => ResourceManager.GetString("strCaminhoBanco", resourceCulture);
    public static string strServidor => ResourceManager.GetString("strServidor", resourceCulture);
    public static string strBanco => ResourceManager.GetString("strBanco", resourceCulture);
    public static string strUsuario => ResourceManager.GetString("strUsuario", resourceCulture);
    public static string strComplemento => ResourceManager.GetString("strComplemento", resourceCulture);
    public static string strSalvarBanco => ResourceManager.GetString("strSalvarBanco", resourceCulture);
    public static string strSucesso => ResourceManager.GetString("strSucesso", resourceCulture);
    public static string strAviso => ResourceManager.GetString("strAviso", resourceCulture);
    public static string strDadosSalvos => ResourceManager.GetString("strDadosSalvos", resourceCulture);
    public static string strInformeCaminho => ResourceManager.GetString("strInformeCaminho", resourceCulture);
    public static string strInformeServidor => ResourceManager.GetString("strInformeServidor", resourceCulture);
    public static string strSenha => ResourceManager.GetString("strSenha", resourceCulture);
    public static string strBandeira => ResourceManager.GetString("strBandeira", resourceCulture);
    public static string strIdiomaDescricao => ResourceManager.GetString("strIdiomaDescricao", resourceCulture);
    public static string strSalvarIdioma => ResourceManager.GetString("strSalvarIdioma", resourceCulture);
}
